# Generated by Django 3.2.3 on 2021-05-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('flag', models.CharField(max_length=16)),
                ('complete', models.BooleanField(default=False)),
                ('complete_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
