# Generated by Django 3.2.3 on 2021-05-28 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_complete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='url',
            field=models.URLField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='complete_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
